// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types manually
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
      }
      employees: {
        Row: {
          id: string
          company_id: string
          user_id: string
          full_name: string
          email: string | null
          role: 'admin' | 'employee'
          created_at: string
        }
        Insert: {
          id?: string
          company_id: string
          user_id: string
          full_name: string
          email?: string | null
          role?: 'admin' | 'employee'
          created_at?: string
        }
        Update: {
          id?: string
          company_id?: string
          user_id?: string
          full_name?: string
          email?: string | null
          role?: 'admin' | 'employee'
          created_at?: string
        }
      }
      attendance_records: {
        Row: {
          id: string
          employee_id: string
          check_in_time: string
          check_out_time: string | null
          latitude: number
          longitude: number
          status: 'present' | 'late' | 'absent'
          created_at: string
        }
        Insert: {
          id?: string
          employee_id: string
          check_in_time: string
          check_out_time?: string | null
          latitude: number
          longitude: number
          status?: 'present' | 'late' | 'absent'
          created_at?: string
        }
        Update: {
          id?: string
          employee_id?: string
          check_in_time?: string
          check_out_time?: string | null
          latitude?: number
          longitude?: number
          status?: 'present' | 'late' | 'absent'
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      employee_role: 'admin' | 'employee'
      attendance_status: 'present' | 'late' | 'absent'
    }
  }
}
